-- Add all 153 Costco Master items in one query
-- Copy/paste this entire file into Supabase Dashboard SQL Editor

INSERT INTO grocery_items (grocery_list_id, display_name, quantity, unit, checked)
SELECT
  gl.id,
  t.item_name,
  1,
  'whole',
  false
FROM grocery_lists gl
CROSS JOIN (VALUES
  ('Muffins'),
  ('apples x2'),
  ('Nectarines'),
  ('Sweet potatoes'),
  ('Peppers'),
  ('Bananas'),
  ('Bagels'),
  ('Potatoes (golden or mini)'),
  ('White onion'),
  ('Whole Carrots'),
  ('mini Cucumbers (check for slime)'),
  ('Celery'),
  ('Cherry tomatoes (on vine)'),
  ('avocados'),
  ('Whole mushrooms (if slimy skip)'),
  ('asparagus (if slimy skip)'),
  ('Broccoli'),
  ('fresh green beans'),
  ('Sweet corn (8 pack)'),
  ('Lemons'),
  ('Limes'),
  ('Salad, if expiry is week+'),
  ('Cauliflower'),
  ('Golden kiwi'),
  ('Cantelope'),
  ('Watermelon'),
  ('Grapes (if plump, fresh)'),
  ('Blueberries (if look fresh)'),
  ('Strawberries (if look fresh)'),
  ('Cara Cara oranges'),
  ('Raspberries'),
  ('Pineapple'),
  ('Plums (honey?)'),
  ('Pears'),
  ('Hummus'),
  ('Rotisserie chicken'),
  ('Tri tip'),
  ('Flank steak'),
  ('Chicken breasts ( tenders'),
  ('Ground Turkey'),
  ('Chicken sausages (no dairy)'),
  ('Italian sausage links'),
  ('Frozen grassfed beef patties'),
  ('Salmon'),
  ('Brats (not Italian)'),
  ('Chicken bites'),
  ('frozen Shrimp (no tail, raw)'),
  ('2x Frozen shrimp tail raw'),
  ('Bitchin sauce'),
  ('Guacamole cups'),
  ('Hummus cups'),
  ('Pickles'),
  ('Kielbasa'),
  ('Gyro meat'),
  ('Tilapia'),
  ('Frozen plain cod'),
  ('egg x 2'),
  ('Almond milk'),
  ('Feta cheese'),
  ('Tillamook 3 pk cracker cut chz'),
  ('Plain green yogurt tub'),
  ('Sparkling water x2'),
  ('Olipop/Poppi (send flavor options)'),
  ('izze pop'),
  ('Spindrift'),
  ('Softener salt x2 blue'),
  ('Paper towels'),
  ('Traeger pellets'),
  ('Kleenex'),
  ('floor Swifters'),
  ('Toilet paper'),
  ('Laundry detergent'),
  ('Kitchen garbage bags'),
  ('Dishwasher pods'),
  ('Dave''s Killer Bread'),
  ('Naan flaoconut shrimp'),
  ('Frzn spring rolls'),
  ('Frozen meal options?'),
  ('Frozen pizzas little'),
  ('Frozen mixed berries'),
  ('Frozen strawberries (only)'),
  ('Frozen pineapple'),
  ('Frozen mango'),
  ('Prdu chx ngs'),
  ('Bare breaded chicken breasts'),
  ('Bare breaded chicken bites'),
  ('frozen chicken strips'),
  ('Frozen breakfast sandwiches'),
  ('Yogurt kefir drinks'),
  ('Chobani yogurt'),
  ('Cheese and nut packs'),
  ('cheese and cracker packs'),
  ('string Cheese sticks'),
  ('simply go gurt sticks'),
  ('Siete almnd flr trtills (by coffee)'),
  ('Flour tortillas (refrigerated)'),
  ('Garlic powder'),
  ('Tomato sauce'),
  ('Diced tomatoes'),
  ('Tomato paste'),
  ('Coconut milk canned'),
  ('Olive salad'),
  ('Ketchup'),
  ('Yellow mustard'),
  ('avocado oil mayo'),
  ('honey'),
  ('BBQ sauce (Kinds)'),
  ('salsa'),
  ('Coffee x2'),
  ('White vinegar'),
  ('Pasta sauce tter'),
  ('Dad cereal'),
  ('triscuits'),
  ('Chicken bouillon jar'),
  ('Beef bouillon jar'),
  ('Olive oil'),
  ('Avocado oil'),
  ('Black beans canned'),
  ('pinto beans canned'),
  ('chickpeas (garbanzo)'),
  ('kidney beans canned'),
  ('Syrup'),
  ('Tuna (wild planet only)'),
  ('Rice seeds of change (orange)'),
  ('Cilantro lime rice pouches'),
  ('beets (cooked)'),
  ('Hippeas'),
  ('Siete chips small bags multi pack'),
  ('lesser evil snack bags'),
  ('boulder canyon chips'),
  ('Honest kids juice boxes'),
  ('Chocolate milk boxes (for kids)'),
  ('unreal drk choc coconut mini'),
  ('brookside drk choc berries'),
  ('Raw mixed nuts'),
  ('Belvitas'),
  ('Archer meat sticks (we have a lot)'),
  ('Raw unsalted cashews'),
  ('raw unsalted almonds'),
  ('Raw unsalted walnuts'),
  ('Pistachio in shells'),
  ('Sprouted Pepita seeds'),
  ('Boom chicka pop kettle corn'),
  ('Peanut butter pretzel bites'),
  ('2x Simple mills cinnamon grahams'),
  ('Simple mills almond crackers'),
  ('Yazzo frozen yogurt bars'),
  ('Chia seeds'),
  ('Tortilla chips'),
  ('Sandwich thins'),
  ('Dots pretzels'),
  ('Crunchmaster crackers'),
  ('Johnny pops')
) AS t(item_name)
WHERE gl.name = 'Costco Master'
  AND gl.household_id = (SELECT household_id FROM users WHERE email = 'jtloudon@me.com');

-- Success! Should return: INSERT 0 153
